#!/bin/sh -e

rm -f "/etc/modules-load.d/neuron.conf"
echo "neuron" | tee -a /etc/modules-load.d/neuron.conf

NEURON_KO=$(find /lib/modules/`uname -r`  -name neuron.ko)

if [ "${kernelver}" = "$(uname -r)" ] && [ -f $NEURON_KO ]; then
    depmod
    modprobe neuron
fi
